let allProducts = [
	{
		id: 1,
		title: 'Ayato Sticker',
		image: 'images/genshin/1.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 2,
		title: 'Dilluc Sticker',
		image: 'images/genshin/2.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 3,
		title: 'Ei Sticker',
		image: 'images/genshin/3.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 4,
		title: 'Hutao Sticker',
		image: 'images/genshin/4.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 5,
		title: 'Kazuha Sticker',
		image: 'images/genshin/5.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 6,
		title: 'Klee Sticker',
		image: 'images/genshin/6.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 7,
		title: 'Scara Sticker',
		image: 'images/genshin/7.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 8,
		title: 'Tighnari Sticker',
		image: 'images/genshin/8.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 9,
		title: 'Xiao Sticker',
		image: 'images/genshin/9.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 10,
		title: 'Yae Sticker',
		image: 'images/genshin/10.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 11,
		title: 'Hinata Sticker',
		image: 'images/haikyuu/1.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 12,
		title: 'Kageyama Sticker',
		image: 'images/haikyuu/2.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 13,
		title: 'Kenma Sticker',
		image: 'images/haikyuu/3.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 14,
		title: 'Kuro Sticker',
		image: 'images/haikyuu/4.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	// {
	// 	id: 15,
	// 	title: 'DIY Keychain',
	// 	image: 'images/haikyuu/4.png',
	// 	price: 35,
	// 	count: 1,
	// 	isInterest: false,
	// 	category: 'Haikyuu',
	// 	size: '2.5 inches x 3.5 inches',
	// 	info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	// },
];

export default allProducts;
