let allProducts = [
	{
		id: 1,
		title: 'DIY Keychain',
		image: 'images/keychain.png',
		price: 35,
		count: 1,
		isInterest: false,
		category: 'Keychain',
		size: '3 inches x 5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 2,
		title: 'Keychain',
		image: 'images/custom_keychain.png',
		price: 45,
		count: 1,
		isInterest: false,
		category: 'Keychain',
		size: '3 inches x 5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 3,
		title: 'DIY Necklace',
		image: 'images/necklace.png',
		price: 30,
		count: 1,
		isInterest: false,
		category: 'Necklace',
		size: '1 inch x 2 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 4,
		title: 'Necklace',
		image: 'images/custom_necklace.png',
		price: 40,
		count: 1,
		isInterest: false,
		category: 'Necklace',
		size: '1 inch x 2 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 5,
		title: 'Ayato Sticker',
		image: 'images/genshin/1.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 6,
		title: 'Diluc Sticker',
		image: 'images/genshin/2.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 7,
		title: 'Ei Sticker',
		image: 'images/genshin/3.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 8,
		title: 'Hutao Sticker',
		image: 'images/genshin/4.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 9,
		title: 'Kazuha Sticker',
		image: 'images/genshin/5.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 10,
		title: 'Klee Sticker',
		image: 'images/genshin/6.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 11,
		title: 'Scaramouche Sticker',
		image: 'images/genshin/7.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 12,
		title: 'Tighnari Sticker',
		image: 'images/genshin/8.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 13,
		title: 'Xiao Sticker',
		image: 'images/genshin/9.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 14,
		title: 'Yae Miko Sticker',
		image: 'images/genshin/10.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Genshin',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 15,
		title: 'Hinata Sticker',
		image: 'images/haikyuu/1.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 16,
		title: 'Kageyama Sticker',
		image: 'images/haikyuu/2.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 17,
		title: 'Kenma Sticker',
		image: 'images/haikyuu/3.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 18,
		title: 'Kuroo Sticker',
		image: 'images/haikyuu/4.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 19,
		title: 'Iwaizumi Sticker',
		image: 'images/haikyuu/5.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 20,
		title: 'Oikawa Sticker',
		image: 'images/haikyuu/6.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Haikyuu',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 21,
		title: 'Chamber Sticker',
		image: 'images/valorant/1.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 22,
		title: 'Gekko Sticker',
		image: 'images/valorant/2.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 23,
		title: 'Jett Sticker',
		image: 'images/valorant/3.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 24,
		title: 'Sage Sticker',
		image: 'images/valorant/4.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 25,
		title: 'Viper Sticker',
		image: 'images/valorant/5.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 26,
		title: 'Yoru Sticker',
		image: 'images/valorant/6.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 27,
		title: 'Reyna Sticker',
		image: 'images/valorant/7.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 28,
		title: 'Neon Sticker',
		image: 'images/valorant/8.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 29,
		title: 'Omen Sticker',
		image: 'images/valorant/9.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
	{
		id: 30,
		title: 'Killjoy Sticker',
		image: 'images/valorant/10.png',
		price: 25,
		count: 1,
		isInterest: false,
		category: 'Valorant',
		size: '2.5 inches x 3.5 inches',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
	},
];

export default allProducts;
